name: Code Review

permissions:
  contents: read
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches: [develop] # Run on PRs against develop branch only
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::795859045189:role/GenAIGitHubActionsServiceRole
          role-session-name: gha-session
          aws-region: us-east-1
      - name: PR review
        uses: bharathvaj-ganesan/code-critique-ai@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          bedrock_retries: 3
          disable_release_notes: true
